version: "3.9"

networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16

services:
  _base: &base
    profiles:
      - _
    image: mitosis:devnet
    build:
      context: ./
      dockerfile: ./infra/devnet/devnet.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: &base_environment
      INFRA_DIR: /infra
      DB_DIR: /db
    volumes:
      - &infra-volume ./infra/devnet:/infra:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "10"

  _geth: &geth
    <<: *base
    entrypoint: /infra/geth/scripts/run-geth.sh

  _mitosisd: &mitosisd
    <<: *base
    environment: &mitosisd-environment
      <<: *base_environment
      MITOSIS_CHAIN_ID: mitosis-devnet-1
      MITOSISD: /usr/bin/mitosisd
      MITOSISD_GENESIS_FILE: /artifacts/genesis-final.json
    volumes:
      - *infra-volume
      - &artifact-volume ./tmp/devnet/init/artifacts:/artifacts:ro

  init:
    <<: *base
    hostname: init
    profiles:
      - init
    entrypoint: /infra/mitosisd/scripts/init.sh
    environment:
      <<: *base_environment
      MITOSIS_CHAIN_ID: mitosis-devnet-1
      MITOSISD: /usr/bin/mitosisd
      ETHOSD: /usr/bin/ethosd
      ETHOS_RPC: http://host.docker.internal:26657
    volumes:
      - *infra-volume
      - ./tmp/devnet/init:/db
    networks:
      common:
        ipv4_address: 172.50.1.1

  node-1-geth:
    <<: *geth
    hostname: node-1-geth
    profiles:
      - node
    environment:
      <<: *base_environment
      ISOLATED_CONFIG_DIR: /infra/geth/config/node-1
    ports:
      - "40303:30303"
      - "18545:8545"
      - "18551:8551"
    volumes:
      - *infra-volume
      - ./tmp/devnet/node-1:/db
    networks:
      common:
        ipv4_address: 172.50.1.1

  node-1-mitosisd:
    <<: *mitosisd
    hostname: node-1-mitosisd
    profiles:
      - node
    entrypoint: /infra/mitosisd/scripts/node.sh
    environment:
      <<: *mitosisd-environment
      EXECUTION_ENDPOINT: http://node-1-geth:8551
      PEER_RPC: val-1-mitosisd:26657
      PEER_P2P: val-1-mitosisd:26656
    ports:
      - "36657:26657" # rpc
      - "19090:9090" # grpc
      - "11317:1317" # api
      - "36660:26660" # prometheus
      - "36656:26656" # p2p
    volumes:
      - *infra-volume
      - *artifact-volume
      - ./tmp/devnet/node-1:/db
    networks:
      common:
        ipv4_address: 172.50.1.2

  val-1-geth:
    <<: *geth
    hostname: val-1-geth
    profiles:
      - validator
    environment:
      <<: *base_environment
      ISOLATED_CONFIG_DIR: /infra/geth/config/val-1
    ports:
      - "50303:30303"
      - "28545:8545"
      - "28551:8551"
    volumes:
      - *infra-volume
      - ./tmp/devnet/val-1:/db
    networks:
      common:
        ipv4_address: 172.50.2.1

  val-1-mitosisd:
    <<: *mitosisd
    hostname: val-1-mitosisd
    profiles:
      - validator
    entrypoint: /infra/mitosisd/scripts/node-for-val.sh
    environment:
      <<: *mitosisd-environment
      EXECUTION_ENDPOINT: http://val-1-geth:8551
      VAL_KEY_FILE: /infra/mitosisd/keys/val-1/priv_validator_key.json
    ports:
      - "46657:26657" # rpc
      - "29090:9090" # grpc
      - "21317:1317" # api
      - "46660:26660" # prometheus
      - "46656:26656" # p2p
    volumes:
      - *infra-volume
      - *artifact-volume
      - ./tmp/devnet/val-1:/db
    networks:
      common:
        ipv4_address: 172.50.2.2

  val-2-geth:
    <<: *geth
    hostname: val-2-geth
    profiles:
      - validator
    environment:
      <<: *base_environment
      ISOLATED_CONFIG_DIR: /infra/geth/config/val-2
    ports:
      - "60303:30303"
      - "38545:8545"
      - "38551:8551"
    volumes:
      - *infra-volume
      - ./tmp/devnet/val-2:/db
    networks:
      common:
        ipv4_address: 172.50.3.1

  val-2-mitosisd:
    <<: *mitosisd
    hostname: val-2-mitosisd
    profiles:
      - validator
    entrypoint: /infra/mitosisd/scripts/node-for-val.sh
    environment:
      <<: *mitosisd-environment
      EXECUTION_ENDPOINT: http://val-2-geth:8551
      VAL_KEY_FILE: /infra/mitosisd/keys/val-2/priv_validator_key.json
      PEER_RPC: val-1-mitosisd:26657
      PEER_P2P: val-1-mitosisd:26656
    ports:
      - "56657:26657" # rpc
      - "39090:9090" # grpc
      - "31317:1317" # api
      - "56660:26660" # prometheus
      - "56656:26656" # p2p
    volumes:
      - *infra-volume
      - *artifact-volume
      - ./tmp/devnet/val-2:/db
    networks:
      common:
        ipv4_address: 172.50.3.2
