version: "3.9"

networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16

x-service-templates:
  _base: &base
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - &infra-volume ./infra/devnet:/infra/devnet:ro
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "10"

  _geth: &geth
    <<: *base
    image: ethereum/client-go:v1.15.11
    entrypoint: /infra/devnet/ec/geth.sh
    environment: &geth-environment
      DATA_DIR: /data
      GENESIS_FILE: /infra/devnet/ec/genesis/genesis.json
    volumes:
      - *infra-volume

  _reth: &reth
    <<: *base
    image: ghcr.io/paradigmxyz/reth:v1.3.12
    entrypoint: /infra/devnet/ec/reth.sh
    environment: &reth-environment
      DATA_DIR: /data
      GENESIS_FILE: /infra/devnet/ec/genesis/genesis.json
    volumes:
      - *infra-volume

  _mitosisd: &mitosisd
    <<: *base
    image: mitosis:devnet
    build:
      context: ./
      dockerfile: ./infra/devnet/mitosisd.Dockerfile
    entrypoint: /infra/devnet/mitosisd/node.sh
    environment: &mitosisd-environment
      MITOSISD: /usr/bin/mitosisd
      MIDEVTOOL: /usr/bin/midevtool
      MITOSISD_HOME: /root/.mitosisd
      MITOSISD_CHAIN_ID: mitosis-devnet-1
      GENESIS_FILE: /artifacts/genesis.json
    volumes:
      - *infra-volume
      - &artifacts-volume ./tmp/devnet/init/artifacts:/artifacts:ro

services:
  init:
    <<: *base
    hostname: init
    profiles:
      - init
    image: mitosis:devnet
    build:
      context: ./
      dockerfile: ./infra/devnet/mitosisd.Dockerfile
    entrypoint: /infra/devnet/mitosisd/init.sh
    environment:
      <<: *mitosisd-environment
      EC_GENESIS_BLOCK_HASH_FILE: /infra/devnet/ec/genesis/genesis-block-hash.txt
      # banana omit eye gesture disagree fork zone cup promote plunge neither rug
      GEN_VAL_MNEMONIC: "YmFuYW5hIG9taXQgZXllIGdlc3R1cmUgZGlzYWdyZWUgZm9yayB6b25lIGN1cCBwcm9tb3RlIHBsdW5nZSBuZWl0aGVyIHJ1Zw=="
      ARTIFACTS_DIR: /artifacts
    volumes:
      - *infra-volume
      - ./tmp/devnet/init/mitosisd:/root/.mitosisd
      - ./tmp/devnet/init/artifacts:/artifacts
    networks:
      common:
        ipv4_address: 172.50.1.1

  node-reth:
    <<: *reth
    hostname: node-reth
    profiles:
      - node
    environment:
      <<: *reth-environment
      MODE: full
      JWT_FILE: /infra/devnet/ec/config/node/jwt.hex
      NODE_KEY_FILE: /infra/devnet/ec/config/node/nodekey
      PEERS_FILE: /infra/devnet/ec/config/node/peers
    ports:
      - "40303:30303"
      - "18545:8545"
      - "18551:8551"
    volumes:
      - *infra-volume
      - ./tmp/devnet/node/reth:/data
    networks:
      common:
        ipv4_address: 172.50.1.1

  node-mitosisd:
    <<: *mitosisd
    hostname: node-mitosisd
    profiles:
      - node
    environment:
      <<: *mitosisd-environment
      MODE: full
      PEER_RPC: genval-mitosisd:26657
      PEER_P2P: genval-mitosisd:26656
      EC_ENDPOINT: http://node-reth:8551
      EC_JWT_FILE: /infra/devnet/ec/config/node/jwt.hex
      GOV_ENTRYPOINT: 0x06c9918ff483fd88C65dD02E788427cfF04545b9
      VAL_MNEMONIC: ""
    ports:
      - "36657:26657" # rpc
      - "19090:9090" # grpc
      - "11317:1317" # api
      - "36660:26660" # prometheus
      - "36656:26656" # p2p
    volumes:
      - *infra-volume
      - *artifacts-volume
      - ./tmp/devnet/node/mitosisd:/root/.mitosisd
    networks:
      common:
        ipv4_address: 172.50.1.2

  genval-geth:
    <<: *geth
    hostname: genval-geth
    profiles:
      - validator
    environment:
      <<: *geth-environment
      MODE: archive
      JWT_FILE: /infra/devnet/ec/config/genval/jwt.hex
      NODE_KEY_FILE: /infra/devnet/ec/config/genval/nodekey
      PEERS_FILE: /infra/devnet/ec/config/genval/peers
    ports:
      - "50303:30303"
      - "28545:8545"
      - "28551:8551"
    volumes:
      - *infra-volume
      - ./tmp/devnet/genval/geth:/data
    networks:
      common:
        ipv4_address: 172.50.2.1

  genval-mitosisd:
    <<: *mitosisd
    hostname: genval-mitosisd
    profiles:
      - validator
    environment:
      <<: *mitosisd-environment
      MODE: archive
      PEER_RPC: ""
      PEER_P2P: ""
      EC_ENDPOINT: http://genval-geth:8551
      EC_JWT_FILE: /infra/devnet/ec/config/genval/jwt.hex
      GOV_ENTRYPOINT: 0x06c9918ff483fd88C65dD02E788427cfF04545b9
      # banana omit eye gesture disagree fork zone cup promote plunge neither rug
      VAL_MNEMONIC: "YmFuYW5hIG9taXQgZXllIGdlc3R1cmUgZGlzYWdyZWUgZm9yayB6b25lIGN1cCBwcm9tb3RlIHBsdW5nZSBuZWl0aGVyIHJ1Zw=="
    ports:
      - "46657:26657" # rpc
      - "29090:9090" # grpc
      - "21317:1317" # api
      - "46660:26660" # prometheus
      - "46656:26656" # p2p
    volumes:
      - *infra-volume
      - *artifacts-volume
      - ./tmp/devnet/genval/mitosisd:/root/.mitosisd
    networks:
      common:
        ipv4_address: 172.50.2.2

  subval-geth:
    <<: *geth
    hostname: subval-geth
    profiles:
      - validator
    environment:
      <<: *geth-environment
      MODE: full
      JWT_FILE: /infra/devnet/ec/config/subval/jwt.hex
      NODE_KEY_FILE: /infra/devnet/ec/config/subval/nodekey
      PEERS_FILE: /infra/devnet/ec/config/subval/peers
    ports:
      - "60303:30303"
      - "38545:8545"
      - "38551:8551"
    volumes:
      - *infra-volume
      - ./tmp/devnet/subval/geth:/data
    networks:
      common:
        ipv4_address: 172.50.3.1

  subval-mitosisd:
    <<: *mitosisd
    hostname: subval-mitosisd
    profiles:
      - validator
    environment:
      <<: *mitosisd-environment
      MODE: full
      PEER_RPC: genval-mitosisd:26657
      PEER_P2P: genval-mitosisd:26656
      EC_ENDPOINT: http://subval-geth:8551
      EC_JWT_FILE: /infra/devnet/ec/config/subval/jwt.hex
      GOV_ENTRYPOINT: 0x06c9918ff483fd88C65dD02E788427cfF04545b9
      # rude mountain surge galaxy leisure torch mother differ buffalo match animal layer
      VAL_MNEMONIC: "cnVkZSBtb3VudGFpbiBzdXJnZSBnYWxheHkgbGVpc3VyZSB0b3JjaCBtb3RoZXIgZGlmZmVyIGJ1ZmZhbG8gbWF0Y2ggYW5pbWFsIGxheWVy"
    ports:
      - "56657:26657" # rpc
      - "39090:9090" # grpc
      - "31317:1317" # api
      - "56660:26660" # prometheus
      - "56656:26656" # p2p
    volumes:
      - *infra-volume
      - *artifacts-volume
      - ./tmp/devnet/subval/mitosisd:/root/.mitosisd
    networks:
      common:
        ipv4_address: 172.50.3.2

  subval-mitosisd-create-validator:
    <<: *mitosisd
    hostname: subval-mitosisd-create-validator
    profiles:
      - create-validator
    entrypoint: /infra/devnet/mitosisd/create-validator.sh
    environment:
      <<: *mitosisd-environment
      EC_RPC_URL: http://subval-geth:8545
      GOV_ENTRYPOINT: 0x06c9918ff483fd88C65dD02E788427cfF04545b9
      VAL_ENTRYPOINT: 0x9866D79EF3e9c0c22Db2b55877013e13a60AD478
      # rude mountain surge galaxy leisure torch mother differ buffalo match animal layer
      VAL_MNEMONIC: "cnVkZSBtb3VudGFpbiBzdXJnZSBnYWxheHkgbGVpc3VyZSB0b3JjaCBtb3RoZXIgZGlmZmVyIGJ1ZmZhbG8gbWF0Y2ggYW5pbWFsIGxheWVy"
      # end alley essay random boost student weather sibling coffee grow again brief
      FUNDER_MNEMONIC: "ZW5kIGFsbGV5IGVzc2F5IHJhbmRvbSBib29zdCBzdHVkZW50IHdlYXRoZXIgc2libGluZyBjb2ZmZWUgZ3JvdyBhZ2FpbiBicmllZg=="
    volumes:
      - *infra-volume
      - *artifacts-volume
      - ./tmp/devnet/subval/mitosisd:/root/.mitosisd
    networks:
      common:
        ipv4_address: 172.50.3.3
